/*
 * -----------------------------------------------------------------------------
 * @author      Ashraf Morningstar
 * @github      https://github.com/AshrafMorningstar
 * @repository  Project Graveyard - The Ultimate Archive
 * @quote       "Code that defines the future. Designed to inspire."
 * -----------------------------------------------------------------------------
*/

/**
 * Portfolio Exporter
 * Author: Ashraf Morningstar
 * GitHub: https://github.com/AshrafMorningstar
 */

class PortfolioExporter {
    constructor() {
        this.JSZip = null;
        this.loadJSZip();
    }

    async loadJSZip() {
        // Load JSZip from CDN
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
        script.onload = () => {
            this.JSZip = window.JSZip;
        };
        document.head.appendChild(script);
    }

    async exportPortfolio(htmlContent, portfolioData) {
        if (!this.JSZip) {
            alert('Export library is still loading. Please try again in a moment.');
            return;
        }

        const zip = new this.JSZip();
        
        // Add the main HTML file
        zip.file('index.html', htmlContent);
        
        // Add a README
        const readme = this.generateReadme(portfolioData);
        zip.file('README.md', readme);
        
        // Generate and download the ZIP
        const blob = await zip.generateAsync({ type: 'blob' });
        this.downloadBlob(blob, 'portfolio.zip');
    }

    generateReadme(data) {
        return `# ${data.fullName || 'My'} Portfolio

This portfolio was generated using Micro Portfolio Generator.

## Deployment Instructions

### Option 1: Netlify
1. Drag and drop this folder to https://app.netlify.com/drop
2. Your site will be live instantly!

### Option 2: Vercel
1. Install Vercel CLI: \`npm i -g vercel\`
2. Run \`vercel\` in this directory
3. Follow the prompts

### Option 3: GitHub Pages
1. Create a new repository on GitHub
2. Upload these files
3. Go to Settings > Pages
4. Select main branch as source
5. Your site will be live at \`https://yourusername.github.io/repo-name\`

## Customization

Feel free to edit \`index.html\` to customize your portfolio further!

---

Generated by [Micro Portfolio Generator](https://github.com/AshrafMorningstar)  
Created by Ashraf Morningstar
`;
    }

    downloadBlob(blob, filename) {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
}

// Create global exporter instance
const exporter = new PortfolioExporter();
