/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

#
# -----------------------------------------------------------------------------
# @author      Ashraf Morningstar
# @github      https://github.com/AshrafMorningstar
# @repository  Project Graveyard - The Ultimate Archive
# @quote       "Code that defines the future. Designed to inspire."
# -----------------------------------------------------------------------------
#

"""
Branding Manager Utility
Author: Ashraf Siddiqui
GitHub: https://github.com/AshrafMorningstar

Handles user branding and attribution in generated projects.
"""

from typing import Dict, Any
from datetime import datetime


class BrandingManager:
    """
    Manages user branding and attribution for generated projects.

    Author: Ashraf Siddiqui
    GitHub: https://github.com/AshrafMorningstar
    """

    def __init__(self, config: Dict[str, Any]):
        """Initialize the branding manager."""
        self.config = config
        self.user_name = config['user']['name']
        self.user_github = config['user']['github']
        self.user_email = config['user'].get('email', '')

    def get_code_header(self, language: str, project_name: str) -> str:
        """
        Generate a code header with author attribution.

        Args:
            language: Programming language
            project_name: Name of the project

        Returns:
            Formatted code header string
        """
        year = datetime.now().year

        # Language-specific comment styles
        comment_styles = {
            'python': ('"""', '"""'),
            'javascript': ('/**', ' */'),
            'typescript': ('/**', ' */'),
            'java': ('/**', ' */'),
            'swift': ('/**', ' */'),
            'go': ('/**', ' */'),
            'rust': ('/**', ' */'),
            'cpp': ('/**', ' */'),
            'c': ('/**', ' */'),
            'ruby': ('=begin', '=end'),
            'php': ('/**', ' */'),
            'html': ('<!--', '-->'),
            'css': ('/**', ' */'),
        }

        start, end = comment_styles.get(language.lower(), ('#', '#'))

        if start in ['"""', '=begin']:
            header = f"""{start}
{project_name}

Author: {self.user_name}
GitHub: {self.user_github}
Year: {year}

Generated by Multi-Language Project Generator Bot
{end}
"""
        elif start in ['/**', '<!--']:
            header = f"""{start}
 * {project_name}
 *
 * Author: {self.user_name}
 * GitHub: {self.user_github}
 * Year: {year}
 *
 * Generated by Multi-Language Project Generator Bot
 {end}
"""
        else:
            header = f"""# {project_name}
#
# Author: {self.user_name}
# GitHub: {self.user_github}
# Year: {year}
#
# Generated by Multi-Language Project Generator Bot

"""

        return header

    def get_readme_content(self, project_name: str, description: str,
                          language: str, setup_instructions: str = "",
                          usage_instructions: str = "") -> str:
        """
        Generate README content with branding.

        Args:
            project_name: Name of the project
            description: Project description
            language: Programming language
            setup_instructions: Setup instructions
            usage_instructions: Usage instructions

        Returns:
            Formatted README content
        """
        year = datetime.now().year

        readme = f"""# {project_name}

{description}

## 📋 Project Information

- **Language**: {language.title()}
- **Author**: {self.user_name}
- **GitHub**: [{self.user_github}]({self.user_github})
- **Year**: {year}
- **Generated by**: Multi-Language Project Generator Bot

## 🚀 Features

This is a fully functional, production-ready project that demonstrates best practices in {language} development.

"""

        if setup_instructions:
            readme += f"""## 📦 Setup Instructions

{setup_instructions}

"""

        if usage_instructions:
            readme += f"""## 💻 Usage

{usage_instructions}

"""

        readme += f"""## 👨‍💻 Author

**{self.user_name}**
- GitHub: [{self.user_github}]({self.user_github})

## 📄 License

MIT License - see LICENSE file for details

## 🤖 About

This project was automatically generated by the Multi-Language Project Generator Bot,
a sophisticated automation tool that creates fully working, production-ready projects
across multiple programming languages.

---

Created with ❤️ by {self.user_name}
"""

        return readme

    def get_package_metadata(self, project_name: str, description: str,
                            version: str = "1.0.0") -> Dict[str, Any]:
        """
        Generate package metadata with author information.

        Args:
            project_name: Name of the project
            description: Project description
            version: Version number

        Returns:
            Dictionary with package metadata
        """
        return {
            "name": project_name.lower().replace(' ', '-'),
            "version": version,
            "description": description,
            "author": self.user_name,
            "github": self.user_github,
            "email": self.user_email,
            "license": "MIT",
            "year": datetime.now().year
        }

    def get_html_meta_tags(self, project_name: str, description: str) -> str:
        """
        Generate HTML meta tags with author information.

        Args:
            project_name: Name of the project
            description: Project description

        Returns:
            HTML meta tags string
        """
        return f"""    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{description}">
    <meta name="author" content="{self.user_name}">
    <meta name="keywords" content="{project_name}, {self.user_name}">
    <title>{project_name} - by {self.user_name}</title>"""

    def get_python_setup_py(self, project_name: str, description: str,
                           version: str = "1.0.0") -> str:
        """
        Generate setup.py content for Python projects.

        Args:
            project_name: Name of the project
            description: Project description
            version: Version number

        Returns:
            setup.py content
        """
        package_name = project_name.lower().replace(' ', '_').replace('-', '_')

        return f'''"""
Setup configuration for {project_name}
Author: {self.user_name}
GitHub: {self.user_github}
"""

from setuptools import setup, find_packages

setup(
    name="{package_name}",
    version="{version}",
    description="{description}",
    author="{self.user_name}",
    author_email="{self.user_email}",
    url="{self.user_github}",
    packages=find_packages(),
    install_requires=[
        # Add your dependencies here
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
)
'''

    def get_package_json(self, project_name: str, description: str,
                        version: str = "1.0.0", dependencies: Dict[str, str] = None) -> str:
        """
        Generate package.json content for Node.js/TypeScript projects.

        Args:
            project_name: Name of the project
            description: Project description
            version: Version number
            dependencies: Project dependencies

        Returns:
            package.json content
        """
        import json

        package_name = project_name.lower().replace(' ', '-')

        package_data = {
            "name": package_name,
            "version": version,
            "description": description,
            "author": {
                "name": self.user_name,
                "url": self.user_github
            },
            "license": "MIT",
            "repository": {
                "type": "git",
                "url": f"{self.user_github}/{package_name}"
            },
            "keywords": [project_name, self.user_name],
            "dependencies": dependencies or {}
        }

        return json.dumps(package_data, indent=2)

    def get_cargo_toml(self, project_name: str, description: str,
                      version: str = "0.1.0") -> str:
        """
        Generate Cargo.toml content for Rust projects.

        Args:
            project_name: Name of the project
            description: Project description
            version: Version number

        Returns:
            Cargo.toml content
        """
        package_name = project_name.lower().replace(' ', '-')

        return f"""[package]
name = "{package_name}"
version = "{version}"
edition = "2021"
authors = ["{self.user_name} <{self.user_email}>"]
description = "{description}"
license = "MIT"
repository = "{self.user_github}/{package_name}"

[dependencies]
"""

    def get_gemspec(self, project_name: str, description: str,
                   version: str = "1.0.0") -> str:
        """
        Generate .gemspec content for Ruby projects.

        Args:
            project_name: Name of the project
            description: Project description
            version: Version number

        Returns:
            .gemspec content
        """
        gem_name = project_name.lower().replace(' ', '_')

        return f'''Gem::Specification.new do |spec|
  spec.name          = "{gem_name}"
  spec.version       = "{version}"
  spec.authors       = ["{self.user_name}"]
  spec.email         = ["{self.user_email}"]

  spec.summary       = "{description}"
  spec.description   = "{description}"
  spec.homepage      = "{self.user_github}/{gem_name}"
  spec.license       = "MIT"

  spec.files         = Dir["lib/**/*", "README.md", "LICENSE"]
  spec.require_paths = ["lib"]

  spec.required_ruby_version = ">= 2.7.0"
end
'''
